name: Onion Scan

on:
  workflow_dispatch:  # 버튼 눌러서 수동 실행할 수 있게 함

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4

      - name: Run scan script
        run: |
          python onion_scan.py
