name: Onion Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '57 15 * * *'  # ✅ 매일 KST 00:57 실행 (UTC 15:57 기준)

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    env:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4
          pip install notion-client

      - name: Run scan script
        run: |
          python onion_scan.py
