name: Onion Scan

on:
  workflow_dispatch:  # 수동 실행 허용
  schedule:
    - cron: '15 13 * * *'  # KST 22:15

permissions:
  contents: write  # GitHub Actions에서 push 가능하게 설정

defaults:
  run:
    shell: bash

jobs:
  run:
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    env:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4
          pip install notion-client

      - name: Run scan script
        run: |
          python onion_scan.py

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push CSV report
        run: |
          git add *.csv
          git commit -m "자동 리포트 업데이트 $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
