name: Onion Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '57 15 * * *'  # 매일 KST 00:57

defaults:
  run:
    shell: bash

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ push 권한 부여됨

    env:
      NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
      NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install beautifulsoup4
          pip install notion-client

      - name: Run scan script
        run: |
          python onion_scan.py

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and push report.csv
        run: |
          git add report.csv
          git commit -m "자동 생성된 CSV 리포트 업데이트 $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
